/**
 */
package graphdelta.provider;

import graphdelta.util.GraphdeltaAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class GraphdeltaItemProviderAdapterFactory extends GraphdeltaAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GraphdeltaItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphdelta.DeltaSequence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeltaSequenceItemProvider deltaSequenceItemProvider;

	/**
	 * This creates an adapter for a {@link graphdelta.DeltaSequence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeltaSequenceAdapter() {
		if (deltaSequenceItemProvider == null) {
			deltaSequenceItemProvider = new DeltaSequenceItemProvider(this);
		}

		return deltaSequenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphdelta.AddNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddNodeItemProvider addNodeItemProvider;

	/**
	 * This creates an adapter for a {@link graphdelta.AddNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddNodeAdapter() {
		if (addNodeItemProvider == null) {
			addNodeItemProvider = new AddNodeItemProvider(this);
		}

		return addNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphdelta.DeleteNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeleteNodeItemProvider deleteNodeItemProvider;

	/**
	 * This creates an adapter for a {@link graphdelta.DeleteNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeleteNodeAdapter() {
		if (deleteNodeItemProvider == null) {
			deleteNodeItemProvider = new DeleteNodeItemProvider(this);
		}

		return deleteNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphdelta.AddEdge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddEdgeItemProvider addEdgeItemProvider;

	/**
	 * This creates an adapter for a {@link graphdelta.AddEdge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAddEdgeAdapter() {
		if (addEdgeItemProvider == null) {
			addEdgeItemProvider = new AddEdgeItemProvider(this);
		}

		return addEdgeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphdelta.DeleteEdge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeleteEdgeItemProvider deleteEdgeItemProvider;

	/**
	 * This creates an adapter for a {@link graphdelta.DeleteEdge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeleteEdgeAdapter() {
		if (deleteEdgeItemProvider == null) {
			deleteEdgeItemProvider = new DeleteEdgeItemProvider(this);
		}

		return deleteEdgeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphdelta.MoveNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MoveNodeItemProvider moveNodeItemProvider;

	/**
	 * This creates an adapter for a {@link graphdelta.MoveNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMoveNodeAdapter() {
		if (moveNodeItemProvider == null) {
			moveNodeItemProvider = new MoveNodeItemProvider(this);
		}

		return moveNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphdelta.ChangeLabel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChangeLabelItemProvider changeLabelItemProvider;

	/**
	 * This creates an adapter for a {@link graphdelta.ChangeLabel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChangeLabelAdapter() {
		if (changeLabelItemProvider == null) {
			changeLabelItemProvider = new ChangeLabelItemProvider(this);
		}

		return changeLabelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphdelta.MoveEdge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MoveEdgeItemProvider moveEdgeItemProvider;

	/**
	 * This creates an adapter for a {@link graphdelta.MoveEdge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMoveEdgeAdapter() {
		if (moveEdgeItemProvider == null) {
			moveEdgeItemProvider = new MoveEdgeItemProvider(this);
		}

		return moveEdgeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (deltaSequenceItemProvider != null)
			deltaSequenceItemProvider.dispose();
		if (addNodeItemProvider != null)
			addNodeItemProvider.dispose();
		if (deleteNodeItemProvider != null)
			deleteNodeItemProvider.dispose();
		if (addEdgeItemProvider != null)
			addEdgeItemProvider.dispose();
		if (deleteEdgeItemProvider != null)
			deleteEdgeItemProvider.dispose();
		if (moveNodeItemProvider != null)
			moveNodeItemProvider.dispose();
		if (changeLabelItemProvider != null)
			changeLabelItemProvider.dispose();
		if (moveEdgeItemProvider != null)
			moveEdgeItemProvider.dispose();
	}

}
